name: Build and deploy

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKER_IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build-push-deploy-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Deploy image on the server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ env.SERVER_HOST }}
          port: ${{ env.SERVER_PORT }}
          username: ${{ env.SERVER_USERNAME }}
          password: ${{ env.SERVER_PASSWORD }}
          script: |
            docker pull ${{ steps.meta.outputs.tags }}
            docker stop ${{ env.DOCKER_IMAGE_NAME }} || true
            docker rm ${{ env.DOCKER_IMAGE_NAME }} || true
            docker run -d --name ${{ env.DOCKER_IMAGE_NAME }} -p 8000:8000 -e POSTGRES_HOST='${{ secrets.POSTGRES_HOST }}' -e POSTGRES_USERNAME='${{ secrets.POSTGRES_USERNAME }}' -e POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}' -e POSTGRES_DATABASE='${{ secrets.POSTGRES_DATABASE }}' -e SPRING_PROFILES_ACTIVE='docker' ${{ steps.meta.outputs.tags }}
